# Generated by Django 3.0.4 on 2020-05-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200513_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ngo',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='ngo',
            old_name='Name',
            new_name='ngo_name',
        ),
        migrations.RenameField(
            model_name='ngo',
            old_name='Type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='user',
        ),
    ]
