# Generated by Django 3.0.4 on 2020-05-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20200514_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='ngo_name',
            new_name='name',
        ),
    ]
